name: Twitter Bot

on:
  schedule:
    - cron: "0 */5 * * *"   # every 5 hours UTC
  workflow_dispatch:        # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore cookies.json
        run: |
          echo "$COOKIES_B64" | base64 -d > cookies.json
        env:
          COOKIES_B64: ${{ secrets.COOKIES_B64 }}

      - name: Run bot
        run: python bot.py
